import React from "react";
import SlideOver from "../../shared/overlay/SlideOver";
import TextField from "../../shared/inputs/TextField";
import ToggleChips, { type ToggleOption } from "../../shared/inputs/ToggleChips";
import Button from "../../shared/inputs/Button";
import type { ProStatus, UserItem, UserRole } from "./types";

type Props = {
  isOpen: boolean;
  onClose: () => void;
  user: UserItem | null;
  onUpdate: (id: string, updates: Partial<Omit<UserItem, "id">>) => void;
};

const roleOptions: ToggleOption[] = [
  { value: "Registered", label: "Registered" },
  { value: "Unregistered", label: "Unregistered" },
];

const proOptions: ToggleOption[] = [
  { value: "Active", label: "Active" },
  { value: "Inactive", label: "Inactive" },
  { value: "None", label: "None" },
];

const EditUserSlideOver: React.FC<Props> = ({
  isOpen,
  onClose,
  user,
  onUpdate,
}) => {
  const [userId, setUserId] = React.useState("USR-0000");
  const [name, setName] = React.useState("");
  const [email, setEmail] = React.useState("");
  const [phone, setPhone] = React.useState("");
  const [country, setCountry] = React.useState("");

  const [role, setRole] = React.useState<UserRole>("Registered");
  const [proStatus, setProStatus] = React.useState<ProStatus>("Inactive");

  const [xpPoints, setXpPoints] = React.useState("0");
  const [avatarUrl, setAvatarUrl] = React.useState("");

  // Prefill on open/user change
  React.useEffect(() => {
    if (!user || !isOpen) return;

    setUserId(user.userId || "USR-0000");
    setName(user.name || "");
    setEmail(user.email || "");
    setPhone(user.phone || "");
    setCountry(user.country || "");

    setRole(user.role);
    setProStatus(user.proStatus);

    setXpPoints(String(user.xpPoints ?? 0));
    setAvatarUrl(user.avatarUrl || "");
  }, [user, isOpen]);

  // Keep state consistent: Unregistered can't be Pro
  React.useEffect(() => {
    if (role === "Unregistered" && proStatus !== "None") {
      setProStatus("None");
    }
    if (role === "Registered" && proStatus === "None") {
      setProStatus("Inactive");
    }
  }, [role, proStatus]);

  const handleSubmit = () => {
    if (!user) return;
    if (!name.trim()) return;

    onUpdate(user.id, {
      userId: userId.trim() || user.userId,
      name: name.trim(),
      email: email.trim() || undefined,
      phone: phone.trim() || undefined,
      country: country.trim() || "Unknown",
      role,
      proStatus,
      xpPoints: Number(xpPoints) || 0,
      avatarUrl: avatarUrl.trim() || undefined,
    });

    onClose();
  };

  return (
    <SlideOver
      isOpen={isOpen}
      onClose={onClose}
      title="Edit User"
      description="Update user profile, account status and Pro state."
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleSubmit}
            disabled={!name.trim() || !user}
          >
            Save Changes
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        <TextField
          label="User ID"
          placeholder="USR-8421"
          value={userId}
          onChange={(e) => setUserId(e.target.value)}
          hint="Optional. Ideally generated by backend."
        />

        <TextField
          label="Full Name"
          placeholder="Enter user's full name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />

        <div className="grid gap-4 sm:grid-cols-2">
          <TextField
            label="Email"
            placeholder="user@example.com"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <TextField
            label="Phone"
            placeholder="+1 555 555 5555"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
          />
        </div>

        <TextField
          label="Country"
          placeholder="Country"
          value={country}
          onChange={(e) => setCountry(e.target.value)}
          hint="Ideally derived from store country; backend should own this."
        />

        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="text-xs font-medium text-slate-200 md:text-sm">
              Account Status
            </label>
            <div className="mt-2">
              <ToggleChips
                options={roleOptions}
                value={role}
                onChange={(v) => setRole(v as UserRole)}
              />
            </div>
          </div>

          <div>
            <label className="text-xs font-medium text-slate-200 md:text-sm">
              Pro
            </label>
            <div className="mt-2">
              <ToggleChips
                options={proOptions}
                value={proStatus}
                onChange={(v) => setProStatus(v as ProStatus)}
              />
            </div>
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <TextField
            label="XP Points"
            type="number"
            min={0}
            value={xpPoints}
            onChange={(e) => setXpPoints(e.target.value)}
          />
          <TextField
            label="Avatar URL"
            placeholder="https://…"
            value={avatarUrl}
            onChange={(e) => setAvatarUrl(e.target.value)}
            hint="Optional. If empty, initials will be used."
          />
        </div>
      </div>
    </SlideOver>
  );
};

export default EditUserSlideOver;
